import { buildParserFile } from "@lezer/generator";
import builtins from "builtin-modules";
import * as chokidar from "chokidar";
import esbuild from "esbuild";
import { readFile, writeFile } from "fs/promises";
import glob from "glob";
import { parse, sep } from "path";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function buildLezerGrammar(path) {
  let input;

  try {
    input = await readFile(path, "utf8");
  } catch (e) {
    return;
  }

  const { dir, name } = parse(path);
  const parserPath = `${dir}${sep}${name}.grammar.ts`;

  let parser, terms;

  try {
    const res = buildParserFile(input, {
      fileName: path,
      includeNames: true
    });

    parser = res.parser;
    terms = res.terms;
  } catch (e) {
    await writeFile(
      parserPath,
      `/*\n${e.stack}\n*/\n\nexport type parser = ${JSON.stringify(
        e.message
      )};\n`
    );

    return;
  }

  await writeFile(parserPath, parser + terms);
}

(async () => {
  const grammarPaths = "src/**/*.grammar";

  if (prod) {
    await Promise.allSettled(
      (await glob(grammarPaths)).map((path) => buildLezerGrammar(path))
    );
  } else {
    const watcher = chokidar.watch(grammarPaths);

    watcher.on("add", buildLezerGrammar);
    watcher.on("change", buildLezerGrammar);
  }

  esbuild
    .build({
      banner: {
        js: banner
      },
      entryPoints: ["src/main.ts"],
      bundle: true,
      external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
      ],
      format: "cjs",
      watch: !prod,
      target: "es2018",
      logLevel: "info",
      sourcemap: prod ? false : "inline",
      treeShaking: true,
      outfile: "main.js"
    })
    .catch(() => process.exit(1));
})();
